#!/usr/bin/env bash

# TODO: ensure node, yarn installed globally

# Create runtime directories if not exist.
mkdir -p .data

# Install dependencies.
npm install
(cd client && npm install)
(cd server && npm install)

# Start either branch depending on production flag
if [ "$1" == "--production" ]
then
    export NODE_ENV="production"
    (cd client && npm run build && mv build ../.build)     # move build dir to this path
    cd server
    npm start
else
    node_modules/.bin/concurrently "cd client && npm start" "cd server && npm start"
fi
