#!/usr/bin/env bash

# Create runtime directories if not exist.
mkdir -p .data .data

# If jekyll directory does not exist, create new jekyll install
if [ ! -d "$DIRECTORY" ]; then
    jekyll new .jekyll
    (cd .jekyll && jekyll b)
fi

# Install dependencies.
(cd client && yarn -s)
(cd server && yarn -s)

# Start either branch depending on production flag
if [ "$1" == "--production" ]
then
    export NODE_ENV="production"
    (cd client && yarn build && mv build ../.build)
    cd server
    yarn -s start
else
    yarn -s
    node_modules/.bin/concurrently "cd client && yarn start" "cd server && yarn start"
fi
